### ISSUE TITLE
Pipeline CI/CD - GitHub Pages

### ISSUE THREAD

**Issue by Rachiid007** [Rachiid007/TaalToolBox#131]
Tâche technique : CI/CD Pipeline avec GitHub Actions. :rocket:

## 📝 Description

En tant que développeur, je souhaite pouvoir déployer automatiquement mon application sur un serveur de production.
La partie **frontend** devrait être déployée sur GitHub Pages et la partie **backend** sur un serveur dédié.

## 📋 Critères d'acceptation

- [x] Le déploiement du frontend se fait automatiquement sur GitHub Pages.
- [ ] Le déploiement du backend se fait automatiquement sur un serveur dédié.
- [x] Le workflow se lance à chaque push ou pull request sur la branche `main`.
- [x] Si les tests unitaires échouent, le déploiement ne se fait pas.
- [ ] Si les tests d'intégration échouent, le déploiement ne se fait pas.
- [ ] Si les tests d'acceptation E2E échouent, le déploiement ne se fait pas.
- [x] Le dossier `/dist` du frontend doit être disponible sur la branche `gh-pages` (il contient le code compilé de l'application Vue.js).

## 🚀 Tâches

- [x] Créer un workflow GitHub Actions.
- [x] **Frontend** : Lancer les tests unitaires, d'intégration et d'acceptation E2E à chaque push ou pull request sur la branche `main`.
- [x] **Backend** : Lancer les tests unitaires, d'intégration et d'acceptation E2E à chaque push ou pull request sur la branche `main`.
- [x] Si les tests unitaires échouent, le déploiement ne se fait pas.
- [x] Si tous les tests passent, déployer le frontend sur GitHub Pages.
- [x] Le déploiement du frontend se fait sur la branche `gh-pages`.
- [ ] Si tous les tests passent, déployer le backend sur un serveur dédié.
- [x] Dans les paramètres de GitHub Pages, activer la source `gh-pages branch`.

## 📌 Complexité : 4 (1-5)

C'est une tâche technique qui nécessite de comprendre comment fonctionne GitHub Actions et comment déployer une application Vue.js sur GitHub Pages.

## 🎯 Priorité : 20

C'est une tâche technique qui est prioritaire car elle permet de déployer automatiquement l'application sur un serveur de production. Cela permet de gagner du temps et d'éviter les erreurs humaines.

## 📦 Dépendances

- [x] Les en **frontend** et **backend** doivent être écrits.
- [x] L'applications doit au moins avoir une page d'accueil.

## 📚 Ressources

- [GitHub Actions](https://docs.github.com/en/actions)
- [GitHub Pages](https://pages.github.com/)
- [Vue.js](https://vuejs.org/)
- [Vite](https://vitejs.dev/)

**Comment by Pourbaix** [comment]
good
