### ISSUE TITLE
En tant qu'élève, je souhaite avoir accès au jeu de flashcard à partir de l'application (sur mon téléphone). (flashcards)

### ISSUE THREAD

**Issue by Pourbaix** [Rachiid007/TaalToolBox#14]
Difficulté:
2 sur 5

**Comment by LouisLombaert** [comment]
**Description**
Lorsque l'élève clique sur un point de la carte de Bruxelles, on lui propose de démarrer une partie. Il pourra donc cliquer sur un bouton "démarrer une partie" pour lancer le jeu de flashcards.
