### ISSUE TITLE
Elève - Choisir le nombre de carte à jouer

### ISSUE THREAD

**Issue by Pourbaix** [Rachiid007/TaalToolBox#15]
# Titre

En tant qu'élève, je souhaite pouvoir choisir le nombre de carte à jouer.(flashcards)

# Complexité:
1 sur 5

**Comment by LouisLombaert** [comment]
Lorsqu'il démarre une nouvelle partie, le joueur peut choisir le nombre de cartes qu'il aura dans son deck (par exemple: soit 5, 10, 15 ou 20).
