### ISSUE TITLE
01. Elève - Choisir le nombre de carte à jouer

### ISSUE THREAD

**Issue by Pourbaix** [Rachiid007/TaalToolBox#16]
# Titre
En tant qu'élève, je souhaite pouvoir choisir le nombre de carte afin de définir la durée de la partie (flashcards).

# Description
Après avoir choisis le nombre de carte qu'il voulait jouer, l'élève disposera d'un deck de flashcards du même nombre de cartes, ces cartes seront choisis aléatoirement par une requête sur la base de donnée.

# Critère d'acceptation

- Une interface permet à l'utilisateur de sélectionner le nombre de carte qu'il souhaite avoir dans son deck au début de la partie.
- L'utilisateur pourra choisir entre 3 possibilité: 20, 10 et 5.
- Ce nombre est stocké pour être utilisé lors du jeu.

# Info technique

La page doit être responsive. Le nombre de carte doit être enregistré et stocké d'une manière à ce qu'il soit utilisable par les autres pages/composants (store).

# Tâche

- Créer une nouvelle page
- Y indiquer les 3 choix sous forme de cartes (20 cartes, 10 cartes ou  5 cartes).
- Pour chaque div (qui sont donc sous forme de carte), créer un bouton qui mène sur la page de début du jeu.
- Au click du bouton stocker le nombre de carte choisi dans le store.

![Image](https://user-images.githubusercontent.com/71372371/195974803-1b53a9b6-908a-48c6-8cf0-b8e5d27308ce.png)

# Complexité
3 sur 5

**Comment by LouisLombaert** [comment]
Après avoir choisis le nombre de carte qu'il voulait jouer, l'élève disposera d'un deck de flashcards du même nombre de cartes, ces cartes seront choisis aléatoirement par une requête sur la base de donnée.
