### ISSUE TITLE
En tant qu'élève, je souhaite que les cartes s'affichent une par une.(flashcards)

### ISSUE THREAD

**Issue by Pourbaix** [Rachiid007/TaalToolBox#17]
Complexité:
2 sur 5

**Comment by LouisLombaert** [comment]
Lorsqu'il démarre une partie, l'élève possède un deck de cartes. La première carte de ce deck s'affiche et l'élève est invité à répondre. Une fois qu'il a répondu, la carte suivante du deck s'affiche, et ainsi de suite.
