### ISSUE TITLE
04. Elève - Décider si j'ai trouvé ou pas une question

### ISSUE THREAD

**Issue by Pourbaix** [Rachiid007/TaalToolBox#19]
# Titre

En tant qu'élève, je souhaite pouvoir sélectionner parmi trois choix : j'ai trouvé, j'y suis presque, je ne trouve pas. (flashcards)

# Description

Une fois que l'utilisateur a vu la solution, il peut s'auto-évaluer en choisissant parmi ces trois choix (j'y suis presque, j'ai trouvé, je ne trouve pas). Cela permettra donc d'influencer le taux d'apparition de la flashcard. Si il a bien répondu, elle ne reviendra plus, si il ne trouve pas, elle devra réapparaitre.

# Complexité:
La US a  une complexité de 1 sur 5

# Valeur d'importance 

Cette US est intéressant car il va permettre à l'utilisateur de s'auto évaluer pour pouvoir indiquer s'il avait la réponse en tête, s'il était presque ou s'il n'a pas trouvé.

# Critères d'acceptation

- Quand l'utilisateur veut savoir la réponse de sa carte , il ne sera pas possible de le voir sans avoir pas clique sur la carte
- Une fois quand il aura cliqué sur la carte, la réponse s'affichera sur l'écran de l'utilisateur où il sera capable de s'auto évaluer 

# Tâches composant  User Story

- Créer un bouton qui valide la réponse si l'élève avait bien la réponse 
- Créer autre bouton  qui dit que l'élève était presque
- Créer le dernier bouton qui dit que l'élève n'a pas trouvé le mot 

# Maquette

![Image](https://user-images.githubusercontent.com/71372488/196877998-9d1fc308-70d5-457e-a240-bb2640ab2c76.png)

-  #5

**Comment by LouisLombaert** [comment]
**Description**
Une fois que l'utilisateur a vu la solution, il peut s'auto-évaluer en choisissant parmi ces trois choix (j'y suis presque, j'ai trouvé, je ne trouve pas). Cela permettra donc d'influencer le taux d'apparition de la flashcard. Si il a bien répondu, elle ne reviendra plus, si il ne trouve pas, elle devra réapparaitre.
