### ISSUE TITLE
06. Elève - Revoir les cartes ratées dans mon deck

### ISSUE THREAD

**Issue by Pourbaix** [Rachiid007/TaalToolBox#20]
# Titre
En tant qu'élève, je souhaite revoir les cartes que je n'ai pas trouvé dans mon deck actuel afin de vérifiez si j'ai assimiler la réponse.

# Description
Si l'utilisateur a trouver la bonne réponse (qu'il a donc répondu "j'ai trouvé"), la carte est donc retiré du deck et il ne pourra plus retomber dessus lors de cette partie. Si il n'a pas trouvé la bonne réponse, la carte reste dans le deck

# Critère d'acceptation
* Si l'utilisateur à cliqué sur "je n'ai pas trouvé" après avoir vu la réponse, la carte doit réapparaitre dans le deck.
* Le nombre de carte restantes dans le deck doit donc resté le même (et ne pas diminuer). 
* La carte doit être rejouer lors de la partie.
* La carte doit être remise aléatoirement dans le deck (on ne sait pas quand elle réapparaitra dans la partie).

# Info technique

# Tâche
* Le bouton "je n'ai pas trouvé" a déjà été créé précédemment, il faudra donc faire en sorte que le clique sur ce bouton fasse revenir la carte dans le deck.
* Il faut remettre la carte dans le deck aléatoirement. 

# Complexité
4 sur 5

**Comment by LouisLombaert** [comment]
**Description**
Si l'utilisateur a trouver la bonne réponse (qu'il a donc répondu "j'ai trouvé"),  la carte est donc retiré du deck et il ne pourra plus retomber dessus lors de cette partie. Si il n'a pas trouvé la bonne réponse, la carte reste dans le deck.
