### ISSUE TITLE
19. Élève - Revoir les cartes non trouvées  dans mes prochains deck selon les calculs des poids

### ISSUE THREAD

**Issue by Pourbaix** [Rachiid007/TaalToolBox#22]
7-En tant qu'élève, je souhaite que les cartes joués se retrouvent dans mes prochains jeux selon leurs poids (Flashcard) afin de bien maîtriser tous les mots

**Comment by LouisLombaert** [comment]
Si l'utilisateur  a répondu "je n'ai pas trouvé", qu'il n'a donc pas trouvé la réponse directement, il aura de bonne chance de retrouver la carte lors d'une prochaine partie.
