### ISSUE TITLE
20. Elève -  je souhaite que mes réponses soit enregistrés pour chaque carte et prise en compte pour le calcul des poids (Flashcards)

### ISSUE THREAD

**Issue by Pourbaix** [Rachiid007/TaalToolBox#27]
----------------------
 HE201916 (Ikram)
----------------------

# Titre
Je souhaite que mes réponses soit enregistrés pour chaque carte et prise en compte pour le calcul des poids (Flashcards)

# Description

Les réponses de l’élève au jeu de Flashcard seront envoyées vers le backend et enregistrées dans la DB pour le calcul des poids (cf US perso #22)

# Critères d'acceptation

Lorsqu'un élève termine un jeu, ses réponses sont sauvegardés dans la DB

# Dépendances techniques

Prérequis : les cartes sont déjà envoyées vers l'utilisateur

# Impact sur la DB

Accès en lecture et écriture sur la DB : écriture des réponses dans la table user_response

# Découpage en tâches

Ajout du endpoint /user_response/iduser/:cards
Implémentation d'une fonction qui permet de mettre à jour la table user_response
 
# Complexité:
3 sur 5

**Comment by LouisLombaert** [comment]
**Description**
Si l'élève trouve une réponse correcte, la carte aura moins de chance de revenir lors d'un prochain quizz. Cependant, plus on avancera dans le temps, plus cette chance s'accroitra. Ainsi, si l'utilisateur a répondu correctement mais que la carte n'est pas réapparue depuis longtemps (exemple: un mois), elle aura de grande chance de réapparaitre.
